### ISSUE TITLE
Generating best grasp for new objects

### ISSUE THREAD

**Issue by anjugopinath** [adithyamurali/TaskGrasp#1]
Hi,

I wanted to generate grasps for a new object.

While I have the point cloud file for the object (I have the .pcd file that I convert to .npy),
could you tell me how to generate the initial gripper point cloud please, that is used by infer.py

pc_file = os.path.join(obj_dir, 'fused_pc_clean.npy')
grasps_file = os.path.join(obj_dir, 'fused_grasps_clean.npy')

Thank You

**Comment by adithyamurali** [comment]
Hi @anjugopinath sorry for my late reply, just saw this.

So in this work we used prior work in sampling stable grasps: https://github.com/GT-RAIL/rail_agile. You'll need to work with ROS to setup this package.

You could also consider other stable grasping algorithms (those that sample 6dof grasps from point clouds) such as:

- Learned grasp sampler: https://github.com/NVlabs/6dof-graspnet, https://github.com/NVlabs/contact_graspnet
- Heuristic Surface Normal sampler: https://github.com/NVlabs/6dof-graspnet/blob/master/surface_normal.py#L42

Fusing multiple point cloud observations of the object will also help you to sample higher quality grasps.

**Comment by anjugopinath** [comment]
Thank You! This answers my question.

**Comment by anjugopinath** [comment]
Hi Adithya,

Are you aware of human hand grasp samplers apart from GraspIt?
Thank You in advance.

**Comment by adithyamurali** [comment]
Unfortunately no sorry. I've only seen papers using GraspIt.

There is also a dataset: https://contactdb.cc.gatech.edu/

**Comment by anjugopinath** [comment]
Thank You!!

**Comment by anjugopinath** [comment]
Thank You again!
