### ISSUE TITLE
About paper

### ISSUE THREAD

**Issue by toolren** [adithyamurali/TaskGrasp#12]
Thank you very much for your team's open source code, from which I have learned a lot. However, regarding the content of the paper, I have some concerns and I hope you can help me clarify them.
1) Does your paper propose a method to filter grab poses based on task instructions? In other words, does the network in your paper have limitations in generating a large number of grab poses from point clouds?

**Comment by adithyamurali** [comment]
Hi @toolren thanks for the qn and interest in the paper. The paper/GCNGrasp network concerns itself with task-oriented grasping based on task instructions (e.g. from language). It decomposes the problem into 1) stable grasp pose generation and 2) discriminative task-oriented evaluation, and GCNGrasp only does the latter. It needs a separate network that proposes stable grasp poses (GPD in this case but you can use others). 

As such, yes, the network is restricted in that way. It is upper bounded by the diversity of grasps generated by the underlying stable grasp generation algorithm

**Comment by adithyamurali** [comment]
hope that clarifies!

**Comment by toolren** [comment]
OH, thanks for your reply, I got it.
