### ISSUE TITLE
Question regarding the status of the mesh objects

### ISSUE THREAD

**Issue by Donglin-Wang2** [adithyamurali/TaskGrasp#2]
Hi,
I am really inspired by your work on task-based grasp detection. I want to use your dataset as a part of my Master's Thesis. I am wondering if the meshes of the objects are available for the public yet.

**Comment by wliu88** [comment]
Hi Donglin,

Thank you for being interested in our paper. Unfortunately, we will not be releasing meshes. However, here are two recent object datasets for you to consider: https://github.com/swtyree/hope-dataset/ and https://github.com/NVlabs/acronym
