### ISSUE TITLE
Query about the mesh models for the dataset

### ISSUE THREAD

**Issue by Connor-ZH** [adithyamurali/TaskGrasp#3]
Hi Adithya,

May I know whether there is any update about your plan to release the mesh models? I would appreciate it a lot if you could kindly share the mesh models with me.

Best, 
Zhang Heng

**Comment by adithyamurali** [comment]
Hi @Connor-ZH 
Sorry for the late reply. Please see this https://github.com/adithyamurali/TaskGrasp/issues/2. Unfortunately we will not be able to release the mesh models.

**Comment by Connor-ZH** [comment]
Hi @adithyamurali,
Thanks a lot for updating me.
