### ISSUE TITLE
Clarification on get_gripper_control_points()

### ISSUE THREAD

**Issue by patrickeala** [adithyamurali/TaskGrasp#4]
Hi @adithyamurali, I would like to clarify why you used 7 points to represent the gripper in get_gripper_control_points(). I noticed there is a duplicate point. What is the purpose of this?

Thanks!

**Comment by adithyamurali** [comment]
Hi @patrickeala the control points are just an approximate representation of the Franka gripper pose and is more compact than using the full gripper mesh. Other papers have also done it - see https://arxiv.org/abs/1905.10520
