### ISSUE TITLE
Wondering about labels in task2_results.txt

### ISSUE THREAD

**Issue by jsll** [adithyamurali/TaskGrasp#5]
Hi,

First of all, thanks for providing the code and the dataset. 

I have a question regarding the labeling of grasps in task2_results.txt. As far as I understand, each line is of the form "{object}-{grasp_index}-{task}:{label}", where each label can either be 1, 0, -1, -2. What is the difference between these four different labels? Is 1 successful, and the rest unsuccessful? Hope you can clarify this issue.

All the best,
Jens

**Comment by abcdsaltfish** [comment]
I guess they're true, weak true, weak false and false. The label is about how success a grasp is.

**Comment by adithyamurali** [comment]
That is correct.
