### ISSUE TITLE
The pretrained model is of limited use.

### ISSUE THREAD

**Issue by abcdsaltfish** [adithyamurali/TaskGrasp#6]
I tried commands like the below to test the pretrained model.
```
python gcngrasp/infer.py cfg/eval/gcngrasp/gcngrasp_split_mode_t_split_idx_3_.yml --data_dir data/taskgrasp/scans --obj_name 124_paint_roller --obj_class paint_roller.n.01 --task brush
```
It only performs when the object has a fine handle like 124_paint_roller. When it comes to objects without a clear handle like 060_scissors, the model shows few green label. And the model can do nothing with a block like 108_bottle or 040_book. Even worse, the model thinks it's better to grasp a knife by its blade while it thinks the hilt is not fit for grasp.

**Comment by adithyamurali** [comment]
i would suggest recent followup papers to verify model improvements: https://github.com/mkt1412/GraspGPT_public

**Comment by abcdsaltfish** [comment]
> i would suggest recent followup papers to verify model improvements: https://github.com/mkt1412/GraspGPT_public

Yeah. Thank you. 

And I can't believe I said these rude words. Sorry.

**Comment by adithyamurali** [comment]
All good :)
