### ISSUE TITLE
When will the object meshes be released?

### ISSUE THREAD

**Issue by skymanaditya1** [adithyamurali/TaskGrasp#7]
Hi,

Thank you for such a massive contribution regarding the dataset of object pointclouds and their task-specific stable grasp poses. However, for a project that I am working on, I need the full object pointcloud or the object mesh as well. I could not find them in the data folder that I downloaded, and there is a line that "object meshes will be released in the future."

Please let me know where I can get the object meshes from.

**Comment by adithyamurali** [comment]
These object meshes would unfortunately not be released.
