### ISSUE TITLE
Task Intents do not seem to be used at all

### ISSUE THREAD

**Issue by Esilocke** [adithyamurali/TaskGrasp#8]
Hi, I would like to use TaskGrasp to perform inference on unknown objects, and was testing the pre-trained model on the examples given and noticed a lot of inconsistencies with the model.
I ran the following with a fixed seed to obtain some fixed grasps:
`python gcngrasp/infer.py cfg/eval/gcngrasp/gcngrasp_split_mode_t_split_idx_3_.yml --obj_name pan --obj_class pan.n.01 --task pour`

and obtained the following probs:
```
[7.31565019e-17 1.00835660e-26 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 3.35938152e-24 0.00000000e+00 1.39360195e-02 9.48255777e-01
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 5.01195148e-35 0.00000000e+00 1.15180841e-25
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 7.37746775e-01 8.56916785e-01 0.00000000e+00 6.92874074e-01
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 8.06931317e-01
 9.46905911e-01 8.34218621e-01 9.40230668e-01 5.37418902e-01
 8.50025654e-01 8.58030379e-01 1.64440729e-36 3.80094434e-25
 0.00000000e+00 0.00000000e+00]
```

I then ran the following task:
`python gcngrasp/infer.py cfg/eval/gcngrasp/gcngrasp_split_mode_t_split_idx_3_.yml --obj_name pan --obj_class pan.n.01 --task cut`

Cut is an irrelevant task for pan, however the returned probs are exactly the same:
```
[7.31565019e-17 1.00835660e-26 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 3.35938152e-24 0.00000000e+00 1.39360195e-02 9.48255777e-01
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 5.01195148e-35 0.00000000e+00 1.15180841e-25
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 7.37746775e-01 8.56916785e-01 0.00000000e+00 6.92874074e-01
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 8.06931317e-01
 9.46905911e-01 8.34218621e-01 9.40230668e-01 5.37418902e-01
 8.50025654e-01 8.58030379e-01 1.64440729e-36 3.80094434e-25
 0.00000000e+00 0.00000000e+00]
```

I verified that this is the case for every task from the knowledge graph. Can I check if this is intended? I have followed the exact steps for installation from your readme, with the only code changes being to fix the seed to fix the grasps being sampled.

**Comment by adithyamurali** [comment]
Hi sorry, I did not get the bandwidth to check this. Closing this. Feel free to open if still an issue. I would also consider checking recent followup works: https://github.com/mkt1412/GraspGPT_public
